// Generated by gencpp from file ros_whill/SetSpeedProfile.msg
// DO NOT EDIT!


#ifndef ROS_WHILL_MESSAGE_SETSPEEDPROFILE_H
#define ROS_WHILL_MESSAGE_SETSPEEDPROFILE_H

#include <ros/service_traits.h>


#include <ros_whill/SetSpeedProfileRequest.h>
#include <ros_whill/SetSpeedProfileResponse.h>


namespace ros_whill
{

struct SetSpeedProfile
{

typedef SetSpeedProfileRequest Request;
typedef SetSpeedProfileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeedProfile
} // namespace ros_whill


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_whill::SetSpeedProfile > {
  static const char* value()
  {
    return "7edfb7c10ea7c5bdda72a3f1fbcf0705";
  }

  static const char* value(const ::ros_whill::SetSpeedProfile&) { return value(); }
};

template<>
struct DataType< ::ros_whill::SetSpeedProfile > {
  static const char* value()
  {
    return "ros_whill/SetSpeedProfile";
  }

  static const char* value(const ::ros_whill::SetSpeedProfile&) { return value(); }
};


// service_traits::MD5Sum< ::ros_whill::SetSpeedProfileRequest> should match
// service_traits::MD5Sum< ::ros_whill::SetSpeedProfile >
template<>
struct MD5Sum< ::ros_whill::SetSpeedProfileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_whill::SetSpeedProfile >::value();
  }
  static const char* value(const ::ros_whill::SetSpeedProfileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_whill::SetSpeedProfileRequest> should match
// service_traits::DataType< ::ros_whill::SetSpeedProfile >
template<>
struct DataType< ::ros_whill::SetSpeedProfileRequest>
{
  static const char* value()
  {
    return DataType< ::ros_whill::SetSpeedProfile >::value();
  }
  static const char* value(const ::ros_whill::SetSpeedProfileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_whill::SetSpeedProfileResponse> should match
// service_traits::MD5Sum< ::ros_whill::SetSpeedProfile >
template<>
struct MD5Sum< ::ros_whill::SetSpeedProfileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_whill::SetSpeedProfile >::value();
  }
  static const char* value(const ::ros_whill::SetSpeedProfileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_whill::SetSpeedProfileResponse> should match
// service_traits::DataType< ::ros_whill::SetSpeedProfile >
template<>
struct DataType< ::ros_whill::SetSpeedProfileResponse>
{
  static const char* value()
  {
    return DataType< ::ros_whill::SetSpeedProfile >::value();
  }
  static const char* value(const ::ros_whill::SetSpeedProfileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_WHILL_MESSAGE_SETSPEEDPROFILE_H
