// Generated by gencpp from file ros_whill/SetSpeedProfileResponse.msg
// DO NOT EDIT!


#ifndef ROS_WHILL_MESSAGE_SETSPEEDPROFILERESPONSE_H
#define ROS_WHILL_MESSAGE_SETSPEEDPROFILERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_whill
{
template <class ContainerAllocator>
struct SetSpeedProfileResponse_
{
  typedef SetSpeedProfileResponse_<ContainerAllocator> Type;

  SetSpeedProfileResponse_()
    : success(false)
    , status_message()  {
    }
  SetSpeedProfileResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetSpeedProfileResponse_

typedef ::ros_whill::SetSpeedProfileResponse_<std::allocator<void> > SetSpeedProfileResponse;

typedef boost::shared_ptr< ::ros_whill::SetSpeedProfileResponse > SetSpeedProfileResponsePtr;
typedef boost::shared_ptr< ::ros_whill::SetSpeedProfileResponse const> SetSpeedProfileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator1> & lhs, const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator1> & lhs, const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_whill

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ec6f3eff0161f4257b808b12bc830c2";
  }

  static const char* value(const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ec6f3eff0161f42ULL;
  static const uint64_t static_value2 = 0x57b808b12bc830c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_whill/SetSpeedProfileResponse";
  }

  static const char* value(const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string status_message\n"
"\n"
;
  }

  static const char* value(const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSpeedProfileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_whill::SetSpeedProfileResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_WHILL_MESSAGE_SETSPEEDPROFILERESPONSE_H
